# Generated by Django 6.0.2 on 2026-08-09 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('area', models.FloatField(blank=True, db_column='area', null=True)),
                ('upn', models.CharField(blank=True, db_column='upn', max_length=25, null=True)),
                ('plot_no', models.CharField(blank=True, db_column='plot_no', max_length=254, null=True)),
                ('land_use', models.CharField(blank=True, db_column='land_use', max_length=254, null=True)),
                ('street_nam', models.CharField(blank=True, db_column='street_nam', max_length=254, null=True)),
                ('owner', models.CharField(blank=True, db_column='owner', max_length=254, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('year_registered', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'parcels',
                'managed': True,
            },
        ),
    ]
