# Generated by Django 6.0.2 on 2026-02-21 18:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('Area', models.FloatField(blank=True, db_column='Area', null=True)),
                ('UPN', models.CharField(blank=True, db_column='UPN', max_length=25, null=True)),
                ('Plot_no', models.CharField(blank=True, db_column='Plot_no', max_length=254, null=True)),
                ('Land_use', models.CharField(blank=True, db_column='Land_use', max_length=254, null=True)),
                ('Street_nam', models.CharField(blank=True, db_column='Street_nam', max_length=254, null=True)),
                ('Owner', models.CharField(blank=True, db_column='Owner', max_length=254, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('year_registered', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'parcels',
                'managed': False,
            },
        ),
    ]
