# Generated by Django 6.0.2 on 2026-08-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'managed': True},
        ),
    ]
