"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
import platform
from pathlib import Path
import dj_database_url

# postgresql://mawuli_estate_db_user:lze74kj7ATummlbg9zAwYYbedPID4ry8@dpg-d9j1aun1dkcs73bjboag-a.frankfurt-postgres.render.com/mawuli_estate_db

# ==================== PATH CONFIGURATION ====================
BASE_DIR = Path(__file__).resolve().parent.parent

# GDAL Library Path (for GeoDjango on Windows)
# Make sure this path matches your QGIS installation
# On Linux (Render/Docker), GDAL is found automatically once installed via apt — no path needed
if platform.system() == "Windows":
    GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.30.2\bin\gdal306.dll"
    GEOS_LIBRARY_PATH = r"C:\Program Files\QGIS 3.30.2\bin\geos_c.dll"

# ==================== SECURITY WARNINGS ====================
# KEEP SECRET KEY SAFE! Falls back to the dev key locally; set SECRET_KEY env var in production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-&n(r^hawzz(sgn!e(qt5-onucmeutjyakc-hcmox+%09mc8rw!'
)

# NEVER run with DEBUG=True in production!
# Defaults to False; set DEBUG=True in a local .env for development.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ==================== ALLOWED HOSTS ====================
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',      # For Render deployment
]

# ==================== INSTALLED APPS ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',           # GeoDjango
    'rest_framework',               # Django REST Framework
    'rest_framework_gis',           # GIS support for DRF
    'corsheaders',                  # CORS handling
    'gisapp',                       # Your custom app
]

# ==================== MIDDLEWARE ====================
# IMPORTANT: CorsMiddleware MUST be at the top
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',      # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serves static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==================== URL CONFIGURATION ====================
ROOT_URLCONF = 'core.urls'

# ==================== TEMPLATES ====================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ==================== WSGI ====================
WSGI_APPLICATION = 'core.wsgi.application'

# ==================== DATABASE ====================
# Uses DATABASE_URL env var when set (Render); falls back to your local Postgres otherwise.
DATABASES = {
    'default': dj_database_url.config(
        default='postgis://postgres:12345678@localhost:5432/mawuli_estate_new',
        engine='django.contrib.gis.db.backends.postgis',
        conn_max_age=600,
    )
}

# ==================== CORS (Cross-Origin Resource Sharing) ====================
# Reads allowed origins from env var (comma-separated); defaults to local dev ports.
# Set CORS_ALLOWED_ORIGINS=https://your-frontend.vercel.app on Render.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177'
).split(',')

# ==================== PASSWORD VALIDATION ====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== INTERNATIONALIZATION ====================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==================== STATIC FILES ====================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


