
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path

# ==================== PATH CONFIGURATION ====================
BASE_DIR = Path(__file__).resolve().parent.parent

# GDAL Library Path (for GeoDjango on Windows)
# Make sure this path matches your QGIS installation
GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.30.2\bin\gdal306.dll"

# ==================== SECURITY WARNINGS ====================
# KEEP SECRET KEY SAFE! For local development only.
SECRET_KEY = 'django-insecure-&n(r^hawzz(sgn!e(qt5-onucmeutjyakc-hcmox+%09mc8rw!'

# NEVER run with DEBUG=True in production!
DEBUG = True

# ==================== ALLOWED HOSTS ====================
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',      # For Render deployment
]

# ==================== INSTALLED APPS ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',           # GeoDjango
    'rest_framework',               # Django REST Framework
    'rest_framework_gis',           # GIS support for DRF
    'corsheaders',                  # CORS handling
    'gisapp',                       # Your custom app
]

# ==================== MIDDLEWARE ====================
# IMPORTANT: CorsMiddleware MUST be at the top
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',      # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==================== URL CONFIGURATION ====================
ROOT_URLCONF = 'core.urls'

# ==================== TEMPLATES ====================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ==================== WSGI ====================
WSGI_APPLICATION = 'core.wsgi.application'

# ==================== DATABASE ====================
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'mawuli_estate_new',
        'USER': 'postgres',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# ==================== CORS (Cross-Origin Resource Sharing) ====================
# For development, allow all origins (temporary)
# When deploying, change this to specific domains only
CORS_ALLOW_ALL_ORIGINS = True   # This allows any frontend to call your API

# For production, you would use this instead:
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5173',
#     'http://localhost:5174',
#     'http://localhost:5175',
#     'http://localhost:5176',
#     'http://localhost:5177',
#     'https://your-frontend.onrender.com',
# ]

# ==================== PASSWORD VALIDATION ====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== INTERNATIONALIZATION ====================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==================== STATIC FILES ====================
STATIC_URL = 'static/'